# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-23 12:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0004_auto_20181123_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_number', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dates',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 23, 17, 45, 15, 954141)),
        ),
        migrations.AlterField(
            model_name='dates',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 23, 17, 45, 15, 954141)),
        ),
    ]
