# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 04:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0006_auto_20181124_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='VStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='dates',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 24, 10, 16, 51, 402000)),
        ),
        migrations.AlterField(
            model_name='dates',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 24, 10, 16, 51, 402000)),
        ),
    ]
