# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 13:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0009_auto_20181124_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 24, 19, 8, 18, 34000)),
        ),
        migrations.AlterField(
            model_name='dates',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 24, 19, 8, 18, 34000)),
        ),
        migrations.AlterField(
            model_name='docsverified',
            name='verification_status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='vstatus',
            name='verification_status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100),
        ),
    ]
