# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 14:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0011_auto_20181124_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regadmin',
            name='user',
        ),
        migrations.AlterField(
            model_name='dates',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 24, 20, 29, 0, 133000)),
        ),
        migrations.AlterField(
            model_name='dates',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 24, 20, 29, 0, 133000)),
        ),
    ]
