# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 15:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0012_auto_20181124_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 24, 20, 32, 10, 422000)),
        ),
        migrations.AlterField(
            model_name='dates',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 24, 20, 32, 10, 422000)),
        ),
        migrations.AlterField(
            model_name='regadmin',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2018, 11, 24, 20, 32, 10, 422000)),
        ),
    ]
