# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 16:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0013_auto_20181124_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='regadmin',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 24, 21, 48, 55, 980000)),
        ),
        migrations.AlterField(
            model_name='dates',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 24, 21, 48, 55, 980000)),
        ),
        migrations.AlterField(
            model_name='regadmin',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2018, 11, 24, 21, 48, 55, 980000)),
        ),
    ]
