# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 17:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0014_auto_20181124_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 24, 22, 40, 49, 55000)),
        ),
        migrations.AlterField(
            model_name='dates',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 24, 22, 40, 49, 55000)),
        ),
        migrations.AlterField(
            model_name='regadmin',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2018, 11, 24, 22, 40, 49, 55000)),
        ),
        migrations.AlterField(
            model_name='regadmin',
            name='email_id',
            field=models.EmailField(default='reg1@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='regadmin',
            name='password',
            field=models.CharField(default=123, max_length=20),
        ),
    ]
