# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-24 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0006_auto_20181123_2149'),
        ('Admins', '0015_auto_20181124_2240'),
    ]

    operations = [
    ]
