# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-27 01:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0017_auto_20181126_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 27, 6, 43, 17, 189780)),
        ),
        migrations.AlterField(
            model_name='dates',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 27, 6, 43, 17, 189780)),
        ),
        migrations.AlterField(
            model_name='regadmin',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2018, 11, 27, 6, 43, 17, 188844)),
        ),
    ]
