# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-23 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('pincode', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('joiningdate', models.DateField(max_length=20)),
            ],
        ),
    ]
