# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-23 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_payment',
            name='applicant_number',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
