# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-20 03:04
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0007_auto_20180620_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('house_no', models.CharField(max_length=20)),
                ('colony_or_location', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=6)),
                ('contact_number', models.CharField(max_length=20)),
                ('emergency_contact_number', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Transgender', 'Trans')], max_length=100)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widow/Widower', 'Widow/Widower'), ('Separated', 'Separated')], max_length=100)),
                ('date_of_birth', models.DateField(default=datetime.datetime(2018, 10, 20, 8, 34, 18, 537012))),
                ('birth_place', models.CharField(max_length=500)),
                ('employement_status', models.CharField(choices=[('PSU', 'PSU'), ('Government', 'Government'), ('Retired Government Servant', 'Retired Government Servant'), ('Self Employed', 'Self Employed'), ('NOt Employed', 'Not Employed'), ('Homemaker', 'Homemaker'), ('Private', 'Private'), ('Student', 'Student'), ('Others', 'Others')], max_length=100)),
                ('pan', models.CharField(max_length=10)),
                ('voter_id', models.CharField(max_length=16)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('guardian_name', models.CharField(max_length=200)),
                ('spouse_name', models.CharField(max_length=200)),
                ('educational_qualification', models.CharField(choices=[('7th pass or less', '7th pass or less'), ('Between 8th and 9th Standard', 'Between 8th and 9th Standard'), ('10th pass and above', '10th pass and above'), ('Graduate and above', 'Graduate and above')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_card', models.FileField(upload_to='')),
                ('address_proof', models.FileField(upload_to='')),
                ('birth_certificate_or_matric_marksheet', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
