# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-20 04:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_details_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='aadhar_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='birth_place',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='colony_or_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='contact_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2018, 10, 20, 9, 43, 3, 662391), null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='educational_qualification',
            field=models.CharField(choices=[('7th pass or less', '7th pass or less'), ('Between 8th and 9th Standard', 'Between 8th and 9th Standard'), ('10th pass and above', '10th pass and above'), ('Graduate and above', 'Graduate and above')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='emergency_contact_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='employement_status',
            field=models.CharField(choices=[('PSU', 'PSU'), ('Government', 'Government'), ('Retired Government Servant', 'Retired Government Servant'), ('Self Employed', 'Self Employed'), ('NOt Employed', 'Not Employed'), ('Homemaker', 'Homemaker'), ('Private', 'Private'), ('Student', 'Student'), ('Others', 'Others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='father_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Transgender', 'Trans')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='guardian_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='house_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widow/Widower', 'Widow/Widower'), ('Separated', 'Separated')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='mother_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='pan',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='pin_code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='spouse_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='voter_id',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
