# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-20 05:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20181020_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2018, 10, 20, 10, 35, 17, 871536), null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='aadhar_card',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='documents',
            name='address_proof',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='documents',
            name='birth_certificate_or_matric_marksheet',
            field=models.ImageField(upload_to=''),
        ),
    ]
