# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-20 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20181020_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
