# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-20 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20181020_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='birth_certificate_or_matric_marksheet',
            field=models.FileField(upload_to=''),
        ),
    ]
