# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-20 05:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20181020_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2018, 10, 20, 11, 0, 47, 433470), null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='aadhar_card',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='documents',
            name='address_proof',
            field=models.FileField(upload_to=''),
        ),
    ]
