# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-21 03:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20181020_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2018, 10, 21, 8, 37, 43, 371837)),
        ),
    ]
