# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-24 01:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20181024_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2018, 10, 24, 7, 23, 46, 743489)),
        ),
        migrations.AlterField(
            model_name='documents',
            name='aadhar_card',
            field=models.FileField(upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='address_proof',
            field=models.FileField(upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='birth_certificate_or_matric_marksheet',
            field=models.FileField(upload_to='documents/%Y/%m/%d/'),
        ),
    ]
