# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-23 03:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20181024_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2018, 11, 23, 8, 38, 24, 836263)),
        ),
        migrations.AlterField(
            model_name='documents',
            name='aadhar_card',
            field=models.FileField(upload_to='Documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='address_proof',
            field=models.FileField(upload_to='Documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='birth_certificate_or_matric_marksheet',
            field=models.FileField(upload_to='Documents/%Y/%m/%d/'),
        ),
    ]
