# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-23 06:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20181123_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2018, 11, 23, 11, 37, 1, 1451)),
        ),
    ]
