# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-23 08:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20181123_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='photo',
            field=models.ImageField(null=True, upload_to='Documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='details',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='aadhar_card',
            field=models.FileField(null=True, upload_to='Documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='documents',
            name='address_proof',
            field=models.FileField(null=True, upload_to='Documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='documents',
            name='birth_certificate_or_matric_marksheet',
            field=models.FileField(null=True, upload_to='Documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
