# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-23 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20181123_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='date_of_appointment',
            field=models.DateField(null=True),
        ),
    ]
