# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-26 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_details_date_of_appointment'),
        ('profiles', '0021_auto_20181123_1830'),
    ]

    operations = [
    ]
