# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-26 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_merge_20181126_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_number', models.CharField(max_length=120, null=True)),
                ('verification_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100)),
            ],
        ),
    ]
